### ISSUE TITLE
Does this work with WordPress.com?

### ISSUE THREAD

**Issue by SamGreenwood1** [devbean/obsidian-wordpress#2]

**Comment by SamGreenwood1** [comment]
I'm getting this error, how do I fix it? 
https://imgur.com/a/rWfeWLK

**Comment by devbean** [comment]
I'm not sure about this error. I need to check it. You could try the latest version of this plugin, it supports REST API now. You can install a WordPress plugin in order to make it work as showed [here](https://devbean.github.io/obsidian-wordpress).

**Comment by devbean** [comment]
I have tried XML-RPC with WordPress.com, it works for me. The error looks like it is because `<` is not escaped by `marked` (while for me it is escaped by `&lt;`). Could you please commit such a post which makes this error? Or please launch obsidian then use CTRL+SHIFT+I shortcuts to open console, see if there is any error or check the plugin output to find out what sends to server.

**Comment by Callileah** [comment]
Hi...   just recently installed the WP plugin w/ Obsidian.  My WP is https://(me).wordpress.com, however running into problem.  When I Publish in Obsidian, it says it can't due to wrong User/PW.  Is this bc it's the WP.com site??  In other words, does the plugin only work if you have your own Site hosted on your own domain?  Thanks for any help with this.

**Comment by SamGreenwood1** [comment]
> I'm not sure about this error. I need to check it. You could try the latest version of this plugin, it supports REST API now. You can install a WordPress plugin in order to make it work as showed [here](https://devbean.github.io/obsidian-wordpress).

But installing plugins on WordPress.com requires the business plan which is way out of my price range.

**Comment by devbean** [comment]
XML-RPC is OK for me on wordpress.com. Could you please check these steps mentioned in https://github.com/devbean/obsidian-wordpress/issues/5#issuecomment-1079879382 ?

**Comment by SamGreenwood1** [comment]
I now have the REST API setup but am now getting a different error:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/20076209/168401129-793a2d8f-948e-4361-958f-84a386a220b5.png">
